### ISSUE TITLE
Debug mode still active when it is disabled in admin panel

### ISSUE THREAD

**Issue by vasilii-b** [Strategery-Inc/Magento2-InfiniteScroll#13]
In admin panel I turned off debug mode, but it continue to show log messages in window's console.

This is because the check is wrong:

` window.SgyIAS = {
        debug: window.iasConfig.mode,
        _log: function(object) {
            if(this.debug) {
                console.log(object);
            }
        },`

In `window.iasConfig.mode` comes the _Items (grid mode)_ from admin settings, but not the debug status (enabled/disabled).

You have to change `window.iasConfig.mode` to `window.iasConfig.debug`

**Comment by gsomoza** [comment]
Thanks for reporting @vasilii-b. This is related to #12, which was just merged to `master`. We'll release a new version as soon as we can merge #11

**Comment by gsomoza** [comment]
In fact this is a bugfix so I just released as 0.2.2
