### ISSUE TITLE
Infinite Scroll not working in Firefox

### ISSUE THREAD

**Issue by sakshi-mobicules** [Strategery-Inc/Magento2-InfiniteScroll#14]
Infinite scroll pagination is not working in firefox.. Its working in chrome. Please fix ..

**Comment by gewaechshaus** [comment]
In our case both browsers are working 
FF 54.0.1 (32-Bit)

You can test it at
https://www.makerdise.com/3d-druck/ersatzteile.html

**Comment by gsomoza** [comment]
Thanks for helping with this @gewaechshaus !
I just verified it's working as well, so I'm closing this ticket for now.
@sakshi-mobicules if you want you can open another ticket with any specific details about what's causing the issues on your end.
