### ISSUE TITLE
Next page of products doesn't show within category

### ISSUE THREAD

**Issue by mikeaccelm** [Strategery-Inc/Magento2-InfiniteScroll#16]
Hello, we've been having an issue with our infinite scroll, where when you go to the next page it doesn't actually show the products that should be on the next page.  It looks like it just shows all the new products like it would on a storefront.

We are working with a t-shirt store, so it's disheartening to see that when you're on maternity shirts or  youth shirts, the next list of shirts are drinking related.

Do you know what could be causing this issue?  It was working until we updated Magento from 2.1.6 to 2.1.9.

**Comment by gsomoza** [comment]
The way the extension works is it simply fetches the next page in the background (via AJAX) and then parses the results to insert them in the current page. So it "should" show whatever is returned by clicking on the "next page" button when InfiniteScroll is not available.

A quick way to test that would be to disable the extension to make sure your pagination works as intended without it. 

If everything works "properly" with the extension disabled, then please let us know, and if possible please send us a log of the AJAX requests made by our extension vs the logs of requests made without the extension so we can compare. Or if you have a live version of the site, then a link to it would also suffice.

**Comment by mikeaccelm** [comment]
Hi Gabriel,

We currently had to disable the infinite scroll extension to get it to work properly.  A live example is located at: https://www.crazydogtshirts.com/funny/menst <https://www.crazydogtshirts.com/funny/menst>

Mike DeJesus  |  Developer
Accelerate Media  |  accelm.com <http://accelm.com/>  |  585.319.5422
300 State St.  Suite 405  |  Rochester NY 14614

**Comment by gsomoza** [comment]
Any chance you could show us the request logs (for AJAX requests) when the extension is enabled? Or "frontend-only" access to an acceptance/staging environment? You can send any private details to contact (at) strategery (dot) io.

**Comment by mikeaccelm** [comment]
Hello,

We sent a message earlier today to your contact email that you’ve provided.  When you get a chance can you confirm that you received it?

Mike DeJesus  |  Developer
Accelerate Media  |  accelm.com <http://accelm.com/>  |  585.319.5422
300 State St.  Suite 405  |  Rochester NY 14614

**Comment by mikeaccelm** [comment]
Hi Gabriel,

Have you found any solution to this?  It appears to be appending a timestamp to the query, which is creating the issue.  We had sent you an email at your strategery email but haven't received a response.

**Comment by damian-pastorini** [comment]
Hi @mikeaccelm I just merged a few fixes and tested the InfinteScroll in a Magento v2.1.9, everything worked fine, do you still have the issue?
If the issue persist:
1 - Do you have any customizations that could be involved? Like a custom theme or module?
2 - Could you provide a URL where we can check it? I just try with https://www.crazydogtshirts.com/funny/menst but there's an error "Service Temporarily Unavailable".
Best,

**Comment by mikeaccelm** [comment]
Hi Damian, we're doing site wide changes right now.  Since, we've decided to go with a different infinite scroll extension.  Thank you for your help.
