### ISSUE TITLE
The latest tag ignored by Composer / support for PHP 7.1

### ISSUE THREAD

**Issue by JanisE** [Strategery-Inc/Magento2-InfiniteScroll#23]
The Packagist has not picked up the latest tag: https://packagist.org/packages/strategery/magento2-infinitescroll

So, Composer does not see it, it downloads only version 0.2.0, which, in turn, does not support PHP 7.1.

**Comment by AntonEvers** [comment]
@damian-pastorini please tag your project as version `0.2.3` in Github. If the version in `composer.json` and the Github tag don't match, composer ignores the version.

**Comment by gsomoza** [comment]
Released `0.2.3` with the latest changes and PHP 7.1 support. Please test well before releasing as there were some changes to the RequireJS configuration – that although they should be backwards compatible, we haven't tested them enough yet to be 100% sure.
