### ISSUE TITLE
Uncaught TypeError: $(...).catalogAddToCart is not a function

### ISSUE THREAD

**Issue by vnahalpara** [Strategery-Inc/Magento2-InfiniteScroll#24]
Hey there,

We install this extension in magento 2.2.1 and we got below error 

Uncaught TypeError: $(...).catalogAddToCart is not a function.

I don't test this with default so may be theme can conflict

**Comment by gsomoza** [comment]
Ok, thanks for reporting! We'll queue up for research. I applied the "help wanted" label in case someone wants to test this against vanilla 2.2.1, to see if it happens there as well.

**Comment by JTessmer** [comment]
This appears to be a simple missing dependency: Adding "catalogAddToCart" to the define dependency array in infinitescroll.js corrects the issue.

**Comment by gsomoza** [comment]
Thanks so much for reviewing that @JTessmer! Any chance you could submit a quick PR to fix it?
