### ISSUE TITLE
A button to load more?

### ISSUE THREAD

**Issue by Zyles** [Strategery-Inc/Magento2-InfiniteScroll#35]
Does this extension have a "Load more products" button? I don't want to load infinitely without the user clicking this button but I don't want pagination.

If not, can it be added?

Thank you.

**Comment by ihor-sviziev** [comment]
By default automatically loads 3 (or 5, i'm not sure) next pages, then "Load more products" button appearing

**Comment by gsomoza** [comment]
You can also customize most things either via configuration options or with a little bit of code.

**Comment by Zyles** [comment]
Got it to work.

Thanks for a good module!
