### ISSUE TITLE
IASPagingExtension is not defined issue in Production mode.

### ISSUE THREAD

**Issue by ghost** [Strategery-Inc/Magento2-InfiniteScroll#39]
Everything is working fine but when we switch into production mode extension is not working. I debug but did not find any issue.
![ajaxscroll_issue](https://user-images.githubusercontent.com/28080068/44342452-a84ed600-a4a8-11e8-9615-06c484aeca08.png)

**Comment by gsomoza** [comment]
Did you already make sure you [re-deployed all static assets](https://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html)?

**Comment by ghost** [comment]
Yes I did everything .

**Comment by Thundar** [comment]
This happens to me too with Magento's JS minification in action. In Chrome debug I see special characters (returns) inside jquery-ias.min.js, related to issue https://github.com/Strategery-Inc/Magento2-InfiniteScroll/issues/10

**Comment by cgsoratto** [comment]
Hi!

I solved this problem by doing this:

app/design/frontend/VENDOR/THEME/etc/view.xml

```
    <exclude>
        <item type="file">Strategery_Infinitescroll::js/jquery-ias.min.js</item>
    </exclude>
```

=D
