### ISSUE TITLE
Fix release 0.2.5 on Packagist

### ISSUE THREAD

**Issue by unicoder88** [Strategery-Inc/Magento2-InfiniteScroll#43]
Good day!

I noticed that tag 0.2.5 exists and attempted to install it, however, only 0.2.4 is found. This is because composer.json has mismatching version: 0.2.4.

Do you think you could fix that?

Thanks :)

**Comment by gsomoza** [comment]
That's the stupid thing about Magento marketplace requiring the "version" attribute on composer.json :)

Good catch – thanks.

**Comment by gsomoza** [comment]
Could you try now?

**Comment by unicoder88** [comment]
Awesome, all cool now!

https://prnt.sc/mpt7wn
