### ISSUE TITLE
Need to implement with third party extension

### ISSUE THREAD

**Issue by CharanjeetE** [Strategery-Inc/Magento2-InfiniteScroll#45]
Hi
I want to use this extension with blog extension which is showing posts and I want show more from this extension on the blog page. Please help me how I can use the code with another extension. Is there any function I can use to show the pagination on blog page.

**Comment by gsomoza** [comment]
You're going to have to use a Magento developer to help you with this.. Since this is a free extension we don't offer free support, sorry..
