### ISSUE TITLE
Publish latest version to packagist.org

### ISSUE THREAD

**Issue by ihor-sviziev** [Strategery-Inc/Magento2-InfiniteScroll#48]
Right now on GitHub we have latest version - 0.3.0, while on packagist.org we have latest version 0.2.5:
https://packagist.org/packages/strategery/magento2-infinitescroll

Could you publish latest version also to packagist.org in order to simplify extension installation?

I thought about workaround - adding github repo to composer.json like this:
```
{
    ...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Strategery-Inc/Magento2-InfiniteScroll.git"
        }
    ]
    ...
}
```

But it didn't worked

Only installing as "dev" package works:
```
composer require strategery/magento2-infinitescroll:"dev-master#83b66c8 as 0.3.0"
```

**Comment by gsomoza** [comment]
This should have been fixed, closing.
