### ISSUE TITLE
Not working in 2.3+

### ISSUE THREAD

**Issue by intheshallow** [Strategery-Inc/Magento2-InfiniteScroll#50]
I tried to get this working in Magento 2.3.2, but it doesn't seem to work. I also tried to change some of the selectors to match other classes, and no such luck.

**Comment by easyoptical** [comment]
Do you mean that you get a blank screen, no infinite scrolling but still the category page, etc?  What happens when you try to run the extension?

If its an exception, can you post an excerpt showing the error from var/log/exception.log and/or your apache/nginx/etc logs?

**Comment by intheshallow** [comment]
Hello,

It doesn't seem to do anything. The page is still running just fine, but the extension doesn't seem to take any effect.

https://www.mccaskillandcompany.com/designers/designers-alex-sepkus/

There is an example link to give you an idea.

I am seeing this error in the Inspector:

Uncaught ReferenceError: IASPagingExtension is not defined

I looked it up, and it seems to be a common error when it comes to Infinite Scrollers when the scripts are combined and minified.

Here are the settings I am also currently using:

https://smhttp-ssl-44145-mccaskill.nexcesscdn.net/pub/media/scroll/Untitled-1.jpg
https://smhttp-ssl-44145-mccaskill.nexcesscdn.net/pub/media/scroll/Untitled-2.jpg

I couldn't find any errors logged in exception.log or system.log that pertained to this issue.

**Comment by intheshallow** [comment]
I seem to have got it working.

I added a etc/view.xml file to my custom theme and added this:

```
<?xml version="1.0"?>

<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/view.xsd">
	<exclude>
	    <item type="file">Strategery_Infinitescroll::js/jquery-ias.min.js</item>
	</exclude>
</view>
```
