### ISSUE TITLE
jQuery is not defined & SgyIAS is not defined

### ISSUE THREAD

**Issue by shyopat** [Strategery-Inc/Magento2-InfiniteScroll#56]
I have installed latest version of this extension getting error in console when i hard refresh ctrl + f5 on catalog page. i couldn't find what cause this issue.

Screenshot for your reference:
![image](https://user-images.githubusercontent.com/46157697/72882713-172d0000-3d29-11ea-81b6-80ebfc75d09c.png)

**Comment by gsomoza** [comment]
Is it possible your theme doesn't have jQuery? We don't bundle it in our plugin.

**Comment by gsomoza** [comment]
Are you able to replicate this issue on a clean M2 installation with the default theme?

**Comment by shyopat** [comment]
Issue resolved 
Changes in requirejs-config.js
var config = {
    paths: {
        'infinitescroll': 'Strategery_Infinitescroll/js/infinitescroll'
    },
    shim: {
            'infinitescroll': {
                deps: ['jquery'] 
            }
    }
};

**Comment by gsomoza** [comment]
ok, thanks for reporting back!

**Comment by gsomoza** [comment]
Are you interested in submitting a PR for this change?
