### ISSUE TITLE
Pagination and back button

### ISSUE THREAD

**Issue by zap263** [Strategery-Inc/Magento2-InfiniteScroll#57]
Hi.. First of all thanks for your work in creating this extension and offering it for free!

I would just like to know if it still supports pagination with the infinite scroll and if a buyer clicks a product and goes back, will they be taken back to where they left off or would they be reverted back to the top of the page?

**Comment by gsomoza** [comment]
Thanks for trying our extension out! If you end up using it and find a way to make it better, please don't hesitate to contribute your fixes/changes back!

For an answer to your question about going "back", please refer to #55
