### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by Axel29** [Strategery-Inc/Magento2-InfiniteScroll#64]
Hi,

I'm trying to upgrade Magento from 2.3.4 to 2.4.0 but I can't because of this extension's version constraint of PHP.
Could you please upgrade it to allow using PHP 7.4 which is now recommended for Magento Cloud 2.4.0?

### Preconditions
1. Magento Cloud v2.4.0
2. PHP 7.4

### Steps to reproduce
1. Install Magento Cloud 2.4.0
2. Install strategery/magento2-infinitescroll via composer

### Expected result
1. Installation is successfull

### Actual result
1. Composer refuses to install the package due to wrong php constraint

![image](https://user-images.githubusercontent.com/3015249/90192746-d7f8f600-ddc3-11ea-8d17-daadf4ae6de1.png)

Thank you,
Axel

**Comment by gsomoza** [comment]
Hi @Axel29, we already have an open PR for 2.4 – see #63  – but we still need to QA it to confirm it works. Is that something you'd be willing to help with?

**Comment by Axel29** [comment]
Hi @gsomoza yeah I would like to test it :-)

**Comment by pikulsky** [comment]
@Axel29 , do you have any results?
I've tested it locally, the module works OK in Magento 2.4.0 (PHP 7.4), no issue so far.

**Comment by ihor-sviziev** [comment]
Hi @Axel29,
We already added PHP 7.4 support in https://github.com/Strategery-Inc/Magento2-InfiniteScroll/pull/63.
I'm closing this issue as it's already resolved.
