### ISSUE TITLE
Extension not working anymore

### ISSUE THREAD

**Issue by Rajat9620** [Strategery-Inc/Magento2-InfiniteScroll#66]
Hello Support,
I have Magento 2.3.4 version where I have installed this extension. It was working fine before but now it is not working anymore.
I havn't made any new changes.
Please check once
https://sandbox.marineparkdistribution.com/

Let me know if you need any thing from my side.
Thanks

**Comment by gsomoza** [comment]
Hi @Rajat9620, we only provide support for out of the box Magento installations. Can duplicate this issue on a clean Magento 2.3.4 installation? I'll reopen the ticket if this is indeed an OOTB issue.
