### ISSUE TITLE
Image not coming

### ISSUE THREAD

**Issue by Vipin1988** [Strategery-Inc/Magento2-InfiniteScroll#68]
Hello,
After scroll in auto loaded product's images not loading. Please let me know asap what is the issue.
for more see here https://naturagrocery.com/all
PFA
![Screenshot from 2020-11-15 14-23-26](https://user-images.githubusercontent.com/7147482/99180688-6461de80-274e-11eb-81c2-dce42d53bf9b.png)

**Comment by ihor-sviziev** [comment]
Hi @Vipin1988,
It seems like you have some image lazy load module that not integrates with the infinite scroll module.
You need to develop such integration yourself. That's the only way to fix your issue.

If you still feel that we have there some bug - let us know.

**Comment by ihor-sviziev** [comment]
Hi @Vipin1988 ,
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!
