### ISSUE TITLE
Scrolling not working when selecting another category from menu.

### ISSUE THREAD

**Issue by ronitd** [Strategery-Inc/Magento2-InfiniteScroll#7]
@gsomoza  @damian-pastorini 
It works fine when we select a category for the first time and then scroll down, the problem starts when we select another category & then scroll down.Though it starts working fine on page refresh.

**Comment by damian-pastorini** [comment]
Hi @ronitd we are a bit overloaded of work for now but we will take a look on the issue as soon we have some time.
Also, if you can give us more info about the environmente will be great, like Magento version, if you are using the sample data, etc.

Thanks!

**Comment by ronitd** [comment]
Hi @damian-pastorini my environment details are 
1. Magento  Community Edition 2.1.0,
2. Magento's sample data,
3. Ubuntu 14.04,
4.Nginx.

**Comment by damian-pastorini** [comment]
Hi @ronitd , we merged a few fixes over today and tested in Magento 2.1.9, which is working fine.
Please make sure to get the fixes from the master branch.
Best,
