### ISSUE TITLE
Next page Products are coming on a new line Instead of Next to the last product of the previous page.

### ISSUE THREAD

**Issue by ronitd** [Strategery-Inc/Magento2-InfiniteScroll#8]
@gsomoza @damian-pastorini 
![screenshot from 2016-10-17 15 35 02](https://cloud.githubusercontent.com/assets/4819409/19433680/5c82567e-947f-11e6-8fbf-41b031342b04.png)

**Comment by damian-pastorini** [comment]
Hi @ronitd , if you like to change that behavior you just need to change the infinitescroll selector configuration.
You can change the selector grid value from: .products-grid
To: .products-grid .product-items .product-item
And that way you will be targeting the items instead the rows.
![image](https://user-images.githubusercontent.com/1211779/32557329-986abac8-c480-11e7-90d0-ce7d6ee6193e.png)
The same apply for the list items.
Best,
